name: rs
channels:
- cqwz
dependencies:
- python=3.6.8
- tensorflow=1.12
- h5py=2.9.0
- gcc-5=5.2.0
- libgcc=7.2.0
- pillow==6.0.0
- pip:
  - petastorm=0.7.2
  - future=0.17.1
  - opencv-python=4.1.0.25
